using System;
using System.Collections.Generic;

namespace Clawsemble
{
    public static class DefaultInstructions
    {
        public static Instruction[] CompileList()
        {
            var instrs = new List<Instruction>();

            instrs.Add(new Instruction("nop", 0x0));
            instrs.Add(new Instruction("vnfo", 0x1));
            instrs.Add(new Instruction("stsz", 0x2));
            instrs.Add(new Instruction("casz", 0x3));
            instrs.Add(new Instruction("plsz", 0x4));
            instrs.Add(new Instruction("rick", 0x5));
            instrs.Add(new Instruction("hcf", 0x6, InstructionArgumentType.String));
            instrs.Add(new Instruction("eop", 0x7));
            instrs.Add(new Instruction("brk", 0x8, InstructionArgumentType.Byte));
            instrs.Add(new Instruction("dbps", 0x9, InstructionArgumentType.String));
            instrs.Add(new Instruction("dbda", 0xa));
            instrs.Add(new Instruction("dbdv", 0xb));
            instrs.Add(new Instruction("mdp", 0xc, InstructionArgumentType.String));
            instrs.Add(new Instruction("mdl", 0xd, InstructionArgumentType.Byte));
            instrs.Add(new Instruction("mdv", 0xe, InstructionArgumentType.Byte));
            instrs.Add(new Instruction("lrl", 0xf, InstructionArgumentType.String));
            instrs.Add(new Instruction("lrd", 0x10));
            instrs.Add(new Instruction("lru", 0x11));
            instrs.Add(new Instruction("fex", 0x12));
            instrs.Add(new Instruction("lc", 0x13, InstructionArgumentType.Number));
            instrs.Add(new Instruction("ld", 0x14, InstructionArgumentType.Byte));
            instrs.Add(new Instruction("ldd", 0x15));
            instrs.Add(new Instruction("dv", 0x16));
            instrs.Add(new Instruction("dp", 0x17));
            instrs.Add(new Instruction("sw", 0x18));
            instrs.Add(new Instruction("swf", 0x19, InstructionArgumentType.Byte));
            instrs.Add(new Instruction("lx", 0x1a, InstructionArgumentType.Number));
            instrs.Add(new Instruction("lxd", 0x1b));
            instrs.Add(new Instruction("lxb", 0x1c, InstructionArgumentType.Number));
            instrs.Add(new Instruction("lxbd", 0x1d));
            instrs.Add(new Instruction("px", 0x1e, InstructionArgumentType.Number));
            instrs.Add(new Instruction("pxd", 0x1f));
            instrs.Add(new Instruction("pxb", 0x20, InstructionArgumentType.Number));
            instrs.Add(new Instruction("pxbd", 0x21));
            instrs.Add(new Instruction("xc", 0x22, InstructionArgumentType.Number));
            instrs.Add(new Instruction("xcb", 0x23, InstructionArgumentType.Number));
            instrs.Add(new Instruction("xcd", 0x24));
            instrs.Add(new Instruction("xci", 0x25, InstructionArgumentType.Array));
            instrs.Add(new Instruction("xs", 0x26, InstructionArgumentType.Byte));
            instrs.Add(new Instruction("xsd", 0x27));
            instrs.Add(new Instruction("xsr", 0x28));
            instrs.Add(new Instruction("xar", 0x29));
            instrs.Add(new Instruction("xr", 0x2a));
            instrs.Add(new Instruction("xrb", 0x2b));
            instrs.Add(new Instruction("xrl", 0x2c));
            instrs.Add(new Instruction("xrlb", 0x2d));
            instrs.Add(new Instruction("xd", 0x2e));
            instrs.Add(new Instruction("xdl", 0x2f));
            instrs.Add(new Instruction("xpo", 0x30));
            instrs.Add(new Instruction("xpi", 0x31, InstructionArgumentType.Byte));
            instrs.Add(new Instruction("xps", 0x32));
            instrs.Add(new Instruction("xpsb", 0x33));
            instrs.Add(new Instruction("xcs", 0x34));
            instrs.Add(new Instruction("xfn", 0x35));
            instrs.Add(new Instruction("xfc", 0x36, InstructionArgumentType.Byte));
            instrs.Add(new Instruction("xmn", 0x37, InstructionArgumentType.Byte));
            instrs.Add(new Instruction("xmb", 0x38, InstructionArgumentType.Byte));
            instrs.Add(new Instruction("xmd", 0x39));
            instrs.Add(new Instruction("xmcn", 0x3a, InstructionArgumentType.Array));
            instrs.Add(new Instruction("xmcb", 0x3b, InstructionArgumentType.Array));
            instrs.Add(new Instruction("xmcd", 0x3c));
            instrs.Add(new Instruction("cnb", 0x3d));
            instrs.Add(new Instruction("cnc", 0x3e, InstructionArgumentType.Number));
            instrs.Add(new Instruction("cbn", 0x3f));
            instrs.Add(new Instruction("jp", 0x41, InstructionArgumentType.Label));
            instrs.Add(new Instruction("jpd", 0x42));
            instrs.Add(new Instruction("jpn", 0x43, InstructionArgumentType.Label));
            instrs.Add(new Instruction("jpp", 0x44, InstructionArgumentType.Label));
            instrs.Add(new Instruction("jppd", 0x45));
            instrs.Add(new Instruction("js", 0x46, InstructionArgumentType.ShortLabel));
            instrs.Add(new Instruction("jsb", 0x47, InstructionArgumentType.ShortLabel));
            instrs.Add(new Instruction("ca", 0x48, InstructionArgumentType.Function));
            instrs.Add(new Instruction("cad", 0x49));
            instrs.Add(new Instruction("cl", 0x4a, InstructionArgumentType.Function));
            instrs.Add(new Instruction("cld", 0x4b));
            instrs.Add(new Instruction("ret", 0x4c));
            instrs.Add(new Instruction("add", 0x4e));
            instrs.Add(new Instruction("sub", 0x4f));
            instrs.Add(new Instruction("mul", 0x50));
            instrs.Add(new Instruction("div", 0x51));
            instrs.Add(new Instruction("mod", 0x52));
            instrs.Add(new Instruction("pow", 0x53));
            instrs.Add(new Instruction("max", 0x54));
            instrs.Add(new Instruction("min", 0x55));
            instrs.Add(new Instruction("and", 0x56));
            instrs.Add(new Instruction("or", 0x57));
            instrs.Add(new Instruction("xor", 0x58));
            instrs.Add(new Instruction("bsl", 0x59));
            instrs.Add(new Instruction("bsr", 0x5a));
            instrs.Add(new Instruction("addc", 0x5b, InstructionArgumentType.Number));
            instrs.Add(new Instruction("subc", 0x5c, InstructionArgumentType.Number));
            instrs.Add(new Instruction("mulc", 0x5d, InstructionArgumentType.Number));
            instrs.Add(new Instruction("divc", 0x5e, InstructionArgumentType.Number));
            instrs.Add(new Instruction("modc", 0x5f, InstructionArgumentType.Number));
            instrs.Add(new Instruction("andc", 0x60, InstructionArgumentType.Number));
            instrs.Add(new Instruction("orc", 0x61, InstructionArgumentType.Number));
            instrs.Add(new Instruction("xorc", 0x62, InstructionArgumentType.Number));
            instrs.Add(new Instruction("bslc", 0x63, InstructionArgumentType.Byte));
            instrs.Add(new Instruction("bsrc", 0x64, InstructionArgumentType.Byte));
            instrs.Add(new Instruction("icr", 0x65));
            instrs.Add(new Instruction("dcr", 0x66));
            instrs.Add(new Instruction("abs", 0x67));
            instrs.Add(new Instruction("rnd", 0x68));
            instrs.Add(new Instruction("sqrt", 0x69));
            instrs.Add(new Instruction("log2", 0x6a));
            instrs.Add(new Instruction("ipw2", 0x6b));
            instrs.Add(new Instruction("neg", 0x6c));
            instrs.Add(new Instruction("not", 0x6d));
            instrs.Add(new Instruction("rev", 0x6e));
            instrs.Add(new Instruction("cbs", 0x6f));
            instrs.Add(new Instruction("cbz", 0x70));
            instrs.Add(new Instruction("land", 0x71));
            instrs.Add(new Instruction("lor", 0x72));
            instrs.Add(new Instruction("lnot", 0x73));
            instrs.Add(new Instruction("eq", 0x74));
            instrs.Add(new Instruction("neq", 0x75));
            instrs.Add(new Instruction("lt", 0x76));
            instrs.Add(new Instruction("lteq", 0x77));
            instrs.Add(new Instruction("gt", 0x78));
            instrs.Add(new Instruction("gteq", 0x79, InstructionArgumentType.Number));
            instrs.Add(new Instruction("eqc", 0x7a, InstructionArgumentType.Number));
            instrs.Add(new Instruction("neqc", 0x7b, InstructionArgumentType.Number));
            instrs.Add(new Instruction("ltc", 0x7c, InstructionArgumentType.Number));
            instrs.Add(new Instruction("lteqc", 0x7d, InstructionArgumentType.Number));
            instrs.Add(new Instruction("gtc", 0x7e, InstructionArgumentType.Number));
            instrs.Add(new Instruction("gteqc", 0x7f));

            return instrs.ToArray();
        }
    }
}